server:
  port:  8006
  
spring:
  application:
    name:  bback
    
  datasource:
    url:  jdbc:mysql://127.0.0.1/s3-bench?useUnicode=true&characterEncoding=UTF-8
    username:  root
    password:  a
    driver-class-name:  com.mysql.jdbc.Driver
  jpa:
    hibernate:
      #ddl-auto: create  # 第一次建表create  后面用update,要不然每次重启都会新建表
    show-sql: true #打印执行的sql语句
    format-sql: true
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect #设置数据库方言  记住必须要使用 MySQL5InnoDBDialect 指定数据库类型对应InnoDB  ;如果使用MySQLDialect 则对应的是MyISAM

logging:
  level:
    com:
      bench:
        Bench: debug
         # dao: debug
         # web: warn




  
    



    
    


