#  yml不能使用制表符tab 只能用普通空格进行缩进
# 设置值使用 :空格(值)
server:
  port: 8888

spring:
  application:
    name: bzuul


zuul:
  routes:
    # 路由名 == 服务名
    test:
      path: /simple/163
      url: http://www.163.com
    # crbook 服务名映射 到 book
    bactile: /actile/**
    # cruser 服务名映射 到 user
    buser: /user/**
    # 默认路由
    base:
      path: /**
      serviceId: bindex

# 解决 zuul 网关报错的问题
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 60000







