server:
  port: 8888

spring:
  application:
    name: bzuul


zuul:
  routes:
    test:
      path: /simple/163
      url: http://www.163.com
    bactile: /actile/**
    buser: /user/**
    base:
      path: /**
      serviceId: bindex

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 60000







